Fix traceback when emailing results report and email 'From' not set (#2807)
* Fix traceback when emailing results report and email 'From' not set

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module bika.lims.browser.publish.emailview, line 84, in __call__
  Module bika.lims.browser.publish.emailview, line 141, in form_action_send
  Module bika.lims.browser.publish.emailview, line 550, in send_email
  Module bika.lims.api.mail, line 241, in send_email
  Module Products.MailHost.MailHost, line 214, in send
  Module Products.MailHost.MailHost, line 436, in _mungeHeaders
MailHostError: Message missing SMTP Header 'From'
```

* Changelog